[package]
name = "exers"
version = "0.1.0"
edition = "2021"
authors = ["Oliwier Michalik"]
description = "Library for compiling and running other code in sandboxed environment"
repository = "https://github.com/olix3001/exers/"
license = "MIT"
readme = "README.md"
keywords = ["sandbox", "wasm", "rust", "compile"]

[dependencies]
derivative = "2.2.0"
tempfile = "3.5.0"
wasi-common = "9.0.1"
wasmtime = "9.0.1"
wasmtime-wasi = "9.0.1"
